from .custom_llama import LlamaModel, LlamaForSequenceClassification
from .custom_mistral import MistralModel, MistralForSequenceClassification as MistralForSequenceClassification
from .modelling_utils import *
import transformers.models
transformers.models.llama.modeling_llama.LlamaModel = LlamaModel
transformers.models.llama.modeling_llama.LlamaForSequenceClassification = LlamaForSequenceClassification
transformers.models.mistral.modeling_mistral.MistralModel = MistralModel
transformers.models.mistral.modeling_mistral.MistralForSequenceClassification = MistralForSequenceClassification